//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelSubscriber
    {
        public ChannelSubscriber()
        {
            this.ChannelSubscriberMessages = new HashSet<ChannelSubscriberMessage>();
        }
    
        public long ID { get; set; }
        public long ChannelID { get; set; }
        public long SubscriberID { get; set; }
        public System.DateTime EFD { get; set; }
        public System.DateTime ETD { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<ChannelSubscriberMessage> ChannelSubscriberMessages { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
