//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMessageAttachment
    {
        public long ID { get; set; }
        public long ChannelMessageID { get; set; }
        public long ChannelMediaID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ChannelMedia ChannelMedia { get; set; }
        public virtual ChannelMessage ChannelMessage { get; set; }
    }
}
