//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMessage
    {
        public ChannelMessage()
        {
            this.ChannelMessageAttachments = new HashSet<ChannelMessageAttachment>();
            this.ChannelSubscriberMessages = new HashSet<ChannelSubscriberMessage>();
        }
    
        public long ID { get; set; }
        public long ChannelID { get; set; }
        public bool SendToAll { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool SendBySMS { get; set; }
        public bool SendByEmail { get; set; }
        public bool IsScheduled { get; set; }
        public System.DateTime ScheduledOn { get; set; }
        public string TimeZoneID { get; set; }
        public short StatusID { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public Nullable<short> SMSStatusID { get; set; }
        public string EmailMessage { get; set; }
    
        public virtual ICollection<ChannelMessageAttachment> ChannelMessageAttachments { get; set; }
        public virtual ICollection<ChannelSubscriberMessage> ChannelSubscriberMessages { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
