//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelSubscriberMessage
    {
        public long ID { get; set; }
        public long ChannelSubscriberID { get; set; }
        public long ChannelMessageID { get; set; }
        public Nullable<System.DateTime> DeliveredOn { get; set; }
        public string TimeZoneID { get; set; }
        public Nullable<System.DateTime> SMSDeliveredOn { get; set; }
        public Nullable<short> SMSStatus { get; set; }
        public Nullable<short> EmailStatus { get; set; }
        public Nullable<decimal> SMSCost { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string MessageSID { get; set; }
        public string SMSErrorCode { get; set; }
        public Nullable<bool> IsMMS { get; set; }
    
        public virtual ChannelMessage ChannelMessage { get; set; }
        public virtual ChannelSubscriber ChannelSubscriber { get; set; }
    }
}
