//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelMedia
    {
        public ChannelMedia()
        {
            this.ChannelMessageAttachments = new HashSet<ChannelMessageAttachment>();
        }
    
        public long ID { get; set; }
        public long ChannelID { get; set; }
        public string Name { get; set; }
        public byte[] Content { get; set; }
        public string MimeType { get; set; }
        public short MediaTypeID { get; set; }
    
        public virtual ICollection<ChannelMessageAttachment> ChannelMessageAttachments { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
