//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupChannels = new HashSet<GroupChannel>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<GroupChannel> GroupChannels { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
