//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRecon
    {
        public long Id { get; set; }
        public string ProfileId { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<decimal> AggregateAmount { get; set; }
        public Nullable<System.DateTime> FinalPaymentDueDate { get; set; }
        public Nullable<System.DateTime> ProfileStartDate { get; set; }
        public Nullable<decimal> CycleAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> NextBillDate { get; set; }
        public Nullable<int> TotalCycles { get; set; }
        public Nullable<int> CyclesCompleted { get; set; }
        public Nullable<int> CyclesRemaining { get; set; }
        public Nullable<int> FailedPmtCount { get; set; }
        public Nullable<System.DateTime> LastPmtDate { get; set; }
        public Nullable<decimal> LastPmtAmt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> AlertCode { get; set; }
        public Nullable<bool> ReconPick { get; set; }
    }
}
