//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrviiAccountMaster
    {
        public PrviiAccountMaster()
        {
            this.PrviiChannelAccountings = new HashSet<PrviiChannelAccounting>();
        }
    
        public long ID { get; set; }
        public string Account { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<PrviiChannelAccounting> PrviiChannelAccountings { get; set; }
    }
}
