//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrviiChannelAccounting
    {
        public long ID { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<byte> Mode { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual PrviiAccountMaster PrviiAccountMaster { get; set; }
    }
}
