//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCartItem
    {
        public ShoppingCartItem()
        {
            this.IosTransactionLogs = new HashSet<IosTransactionLog>();
        }
    
        public long ID { get; set; }
        public long ShoppingCartID { get; set; }
        public long ChannelID { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string PayerId { get; set; }
        public Nullable<short> PaymentStatusID { get; set; }
        public string PaymentProfileID { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public Nullable<short> BillingPeriodID { get; set; }
        public short BillingFrequency { get; set; }
        public short TotalBillingCycles { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<short> ProfileStatus { get; set; }
        public Nullable<byte> PaymentMode { get; set; }
    
        public virtual ShoppingCart ShoppingCart { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual ICollection<IosTransactionLog> IosTransactionLogs { get; set; }
    }
}
