//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionReconDetail
    {
        public long Id { get; set; }
        public string TransactionId { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string PayerDisplayName { get; set; }
        public Nullable<int> Type { get; set; }
        public string ProfileId { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string EndDate { get; set; }
        public string PriceDistribution { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public Nullable<long> SubscriberId { get; set; }
        public string ChannelName { get; set; }
    }
}
