//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.ChannelSubscribers = new HashSet<ChannelSubscriber>();
            this.UserRoles = new HashSet<UserRole>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.UserDeviceInfoes = new HashSet<UserDeviceInfo>();
        }
    
        public long ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public bool IsActive { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public long CountryID { get; set; }
        public string ZipCode { get; set; }
        public string DeliveryMechanisms { get; set; }
        public short DeviceTypeID { get; set; }
        public string NickName { get; set; }
        public string TimeZoneID { get; set; }
        public Nullable<long> StateID { get; set; }
        public string City { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<long> ChannelID { get; set; }
    
        public virtual ICollection<ChannelSubscriber> ChannelSubscribers { get; set; }
        public virtual Country Country { get; set; }
        public virtual Group Group { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        public virtual ICollection<UserDeviceInfo> UserDeviceInfoes { get; set; }
    }
}
