//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prvii.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeviceInfo
    {
        public long Id { get; set; }
        public Nullable<long> SubscriberId { get; set; }
        public string DeviceCordova { get; set; }
        public string DevicePaltform { get; set; }
        public string DeviceId { get; set; }
        public string DeviceVersion { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DeviceToken { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
